pwem/convert/headers.py
pwem/convert/image_handler.py
pwem/xmipp-ghost/xmippLib.py

ImageHandler getDimensions: use ccp4header when possible
Ghost changes to reach further without xmipp.

Ccp4Header --> consider path :mrc "decoration"

---

pwem/__init__.py
pwem/convert/atom_struct.py
pwem/protocols/protocol_import/volumes.py

(1) modify maxit installation so we may reuse the same function from another plugins. (2) add double quotes around filenames in volume import, otherwise maxit  fails if directory name has spaces

modify maxit installation and fix bug related with filenames that contains spaces

---

pwem/objects/data.py

We are adding more general parameters to the Acquistion class. 
Right now only Relion is making use of it, but maybe other programs will do. 
copyInfo now needs to copy these new attributes as well.

Extend Acquisition class

---

pwem/metadata/classes.py

Simple extension to the Row class that contains internally a dict with labels and values.
This extension will allow us to smoothly switch between this class and a simple dict  with key, value pairs as a row, that we use when dealing with some Relion conversions.

Added get/setitem to Row class to behave as dict

---

pwem/emlib/metadata/utils.py
pwem/objects/data.py

Two changes:
* Added set/get as aliases for getValue/setValue in Row class
* Added flag doClone to copyItems. By default, it works as before, but avoiding the clone should have a good impact in performance, tested in some Relion protocols. Improved docstring for that function.

Minor API additions

---

pwem/convert/headers.py
pwem/emlib/image/image_handler.py
pwem/protocols/protocol_import/volumes.py
pwem/tests/data/test_data.py

ImageHandler-ccp4header: add test to check all file and variations of the annotations.

Jj fix headers single vol

---

pwem/protocols/protocol_import/base.py
pwem/protocols/protocol_import/volumes.py
pwem/tests/protocols/test_protocols_import_volumes.py

1) If import volume produces  a new set of half maps then the name of the new  half maps was not stored in the volume object. This bug has been fixed
2) add another check to validate. If pattern is provided then the option half maps cannot be used
The corresponding test has been created
scipion3 tests pwem.tests.protocols.test_protocols_import_volumes

Fix import protocol

---

pwem/protocols/protocol_export/protocol_export_DB.py
pwem/tests/protocols/test_protocol_export2DB.py
pwem/viewers/viewer_chimera.py

Dear all,
we have modified the protocol export2DB to save sampling and origin in the header of each map or mask that the user would like to export.
Test:
scipion3 tests pwem.tests.protocols.test_protocol_export2DB.TestExport2DataBases

Export to DataBases

---

pwem/protocols/protocol_import/volumes.py

Hi all,
here you are a tiny pull request to solve one import volumes from EMDB failing test since it did not generate the appropriate output. We have replaced the original Ccp4Header by emconv.Ccp4Header.
Test: 
scipion3 tests pwem.tests.protocols.test_protocols_import_volumes.TestImportVolumes

Mm emconv ccp4 header

---

pwem/convert/headers.py
pwem/emlib/image/image_handler.py

This PR includes:
- Changes in headers.py to read .st and .rec (usually IMOD extensions) as .mrc natively in Scipion (without Xmipp)

Read header as .mrc

---

pwem/wizards/wizard.py

Fixes #106:
Wizard box size problema solved. Mask radius values in pixels are now coherent with the box size.

Jj fix radius wizard

---

pwem/__init__.py
pwem/protocols/__init__.py
pwem/protocols/protocol_metadata_editor.py
pwem/viewers/views.py

This protocol is to generically edit an item in a set. 
We've had 2 cases already for this:
1.- set "amplitude contrast" to a different value of the one specified at import time. It seems (the case is reasonable under certain circumstances)
2.- Set random values to some metadata attributes. This escapes any standard image processing, but was needed to make test and evaluate image processing protocols when data is wrong.
It also passes Scipion DEBUG mode to ShowJ.

Metadataeditor

---

pwem/viewers/viewer_chimera.py

Allows chimera to force format. Let us imagine  that we have a volume with extension "xxx" in spider format. By default chimera assumes that only files with extension .vol and .spi are spider files therefore it will fail. With this modification we can pass chimera information about the format that will supersede  the extension.

Rm chimerax

---

pwem/convert/atom_struct.py
pwem/protocols/protocol_alignment_invertHand.py

add renumber and rename functions to atom_struct.py which allows to shift the residues  position by an offset and change the chain name
Also a have modified the format used by invert_hand protocol to print the progressbar 
since scipion uses variable fonts so the bar size changes in each print
because   the "space" width is different from the "=" width

Rm atom struct

---

pwem/wizards/wizard.py

Inheritance diverges at some point in terms of the cases with/without downsampling entry. Read input when needed, return 1 otherwise.

fixes #151

---

pwem/objects/data.py
pwem/protocols/protocol_alignment_assign.py
pwem/protocols/protocol_extract_coordinates.py

This fixes 2 issues:
1.- shift in Z of projection alignment are 0 (before some value was written due to Transfor.scaleShifts working on the non inverted matrix
2.- When combining extract coordinates with assign angles final shift should be more accurate.
I'd like to discuss this with @delarosatrevin. This PR implies setting xFrac and yFrac in the Coordinate object for future alignment assign. They can be removed at alignment assign time and we can avoid asking since new attributes can be detected.

Fix assign angles shifts before

---

pwem/__init__.py
pwem/viewers/viewer_volumes.py

This fixes the viewer since from the last update the tmp folder does not remain after protocol execution.
So viewer should not assume tmp exists anymore. We use extra now, Another option would be to use system /tmp if it is actually temporary.

do not use tmp path for chimera viewer

---

pwem/protocols/protocol_movies.py

In case when SCIPION_SCRATCH is set, abs links are required for files inside tmp folder

use abs path for tmp symlinks

---

pwem/convert/atom_struct.py
pwem/protocols/protocol_import/sequence.py
pwem/protocols/protocol_import/volumes.py
pwem/protocols/protocol_origin_sampling_volume.py
pwem/viewers/viewer_sequence.py

Hi all,
some small changes are included in this pull request to fix some general small errors, among them:
* Visualization of sequences (USER_SEQ.txt file saved now in extra folder).
* Downloading of an atomic structure before opening its sequence (case 3rrq in TestChimeraModellerSearch, which failed previously)
* Added default values of x, y, z origin coordinates and not assigned the 'mrc' extension when the input map is not copied,
Tests:
scipion3 tests pwem.tests.protocols.test_protocols_import_sequence.TestImportSequence
scipion3 tests chimera.tests.test_protocol_modeller_search.TestChimeraModellerSearch
scipion3 tests pwem.tests.protocols.test_protocols_assign_orig.TestOriginSampling

1 mm scipion3 sampling inspect chain

---

pwem/protocols/protocol_movies.py

Ctf and picking protocols do have a DONE folder in extra, but movie alignment protocols seem to dump txt files directly into extra. This should fix this.

create DONE folder in extra

---

pwem/convert/atom_struct.py
pwem/protocols/protocol_origin_sampling_volume.py
pwem/tests/data/test_convert_atom_struct.py
pwem/viewers/viewer_chimera.py
pwem/viewers/viewer_volumes.py

Added function   getTransformMatrix and getBoundingBox which find the matrix that Superimposes two atom structures and, for a given atom structure, its bounding box.
tests:
scipion3 tests pwem.tests.data.test_convert_atom_struct.TestAtomicStructHandler.testGetTransformMatrix
scipion3 tests pwem.tests.data.test_convert_atom_struct.TestAtomicStructHandler.testGetBoundingBox
===========
I have also added the command "view" to the chimera visualization script. In this way  all loaded elements are in the view field. By default chimera uses the first loaded element to define the view field. That is if you load first a small object and then a large one you will no see the large one. View redefines the view field so all objects are visible

Rm transformation matrix

---

pwem/utils.py
requirements.txt

Previous versions than 2021.3.4 works and are compatible with older pythons than 3.7, but they print a warning in the terminal.

Do not fix the version of tifffile. 

---

pwem/protocols/protocol_import/volumes.py

function "fetch_emdb_map" retrieves a 3D map from PDB server. Sometimes the connection between scipion and EMDB is not great and the function may fail.
I modified it so it tries nTimes (by default nTimes=3) before raising an exception. 
If you want to test it uncomment the line 
Implementation note:  Loop statements may have an else clause; it is executed when the loop terminates through exhaustion of the iterable

modify function fetch_emdb_map so retries if there is an error

---

pwem/viewers/viewer_chimera.py

Hi all,
here you have a tiny fix since otherwise the words "stick" and "view" are only one word avoiding visualizing results in ChimeraX (an atomic structure imported in this case).

Added page break to allow the opening of text .cxc file

---

pwem/objects/data.py

This PR includes:
- Fixes in CTFModes,  __str__ method. Astigmatism is equal to the defocus difference (no defocusAngle)

fixes in ctfStr astigmatism definition

---

pwem/wizards/wizards_3d/__init__.py
pwem/wizards/wizards_3d/callbacks.py
pwem/wizards/wizards_3d/mask_structure_wizard.py
pwem/wizards/wizards_3d/mask_volume_wizard.py

Two new wizards have been added to the `wizards/wizards_3d` folder including the following functionalities:
- `mask_strcuture_wizard`: This wizard opens an `Atomic Structure` with Matplotlib to define a spherical mask or an origin. The values returned by the wizard are the radius of the sphere defining the mask and the origin of the sphere (it can return both or just one depending on the application).
-  `mask_volume_wizard`: This wizard opens a `Volume` with Matplotlib to define a spherical mask or an origin. The values returned by the wizard are the radius of the sphere defining the mask and the origin of the sphere (it can return both or just one depending on the application).
By default, the wizard returns the origin of the sphere following the Xmipp convention (coordinates x,y,z are …

New 3D Wizards for Mask/Origin Selection

---

pwem/protocols/__init__.py
pwem/protocols/protocol_movie_eraser.py

Useful combined with empiar downloader and save space, providing you do not want movies afterwards
By default runs in "dry mode": a boolean param that is hidden.
A warning is shown if dry mode is deactivated.

Protocol to remove movies already processed

---

pwem/objects/data.py

This PR includes:
- Changes in standardize method in CTFModel to protect from potential errors in defocus ratio calculation (division by cero)

Protect defocus ratio calculation in standarize method (CTFModel)

---

pwem/tests/workflows/test_workflow_modeling.py

Hi all,
here you have some small changes to fix the atomic structure output names according to the protocol number since it started to fail after some scipion3 update. Only the test has been modified and you can check that it works properly with:
scipion3 tests pwem.tests.workflows.test_workflow_modeling

Fixed atomic structure output names in test

---

pwem/protocols/protocol_particles_picking.py

Fix methods. The reason is cryolo produces a boxSize integer output which gives an error for methods section.

only iterate over coords sets

---

CHANGES.txt
pwem/__init__.py
pwem/viewers/viewer_chimera.py

This PR tries to get the CHIMERA_HOME from the chimera plugin itself. This way any future chimeraX update will not require to release this code.
In the future, maybe code here using chimera could be moved to chimera plugin, but this is not done here.
Increase JAVA max memory to 4GB

Try to get CHIMERA_HOME from chimera plugin.

---

pwem/emlib/image/image_handler.py
pwem/protocols/protocol_movies.py

.gain gain reference file from Falcon 4 / EPU is a tif file. Since xmipp cant recognize it as tif (but rather unknown spider file), I make a tmp link before actual conversion to mrc. The link has to be absolute for cases when tmp is on separate scratch disc

link .gain as .tif file before conversion

---

pwem/tests/workflows/test_workflow_xmipp_ctf_consensus.py

-Test_workflow_xmipp_ctf_consensus.py had three values regarding the CTF estimation (defocus U & V and Angle) that needed to be updated since the ctf estimation algorithms have change the way to estimate them.

test_workflow_xmipp_ctf_consensus.TestCtfConsensus Updated

---

pwem/protocols/protocol_import/coordinates.py
pwem/protocols/protocol_import/dataimport.py
pwem/tests/protocols/test_protocols_import_coords.py

Add to import coordinate protocol the option "import from scipion"
Test
scipion3 tests pwem.tests.protocols.test_protocols_import_coords.TestImportCoordinates
By the way this test checks import  coordinates from any package, therefore if some package is missing you will get an error.

add import coordinates from scipion to import coordiantes

---

pwem/protocols/protocol_align_movies.py

Turns out that Enum can't have two items with the same value and keep them separately.

Possible output os movie alignment changed to dictionary.

---

pwem/viewers/viewers_data.py

Right-clicking a SetOfNormalModes gave an option to use the DataViewer because it was set as a target for it, but clicking that didn't do anything.
Now, I've added an entry to _visualize for that target so it works.

fixed DataViewer for SetOfNormalModes

---

pwem/objects/data.py
pwem/protocols/protocol_set_filter.py

The output sqlite database generated with the previous code was "pockets..sqlite" (note the double point). 
should it be fixed in the createCopy method?

sqlite with ..

---

pwem/protocols/protocol_import/volumes.py

EMDB entries with IDs shorter than 4 characters have prepending zeros e.g. 0774 so we need to take that into account to fetch them. Without the fix, I get the following error:
```
localFileName, sampling, origin = fetch_emdb_map(774, directory='.', tmpDirectory='.')
Error retrieving data from EMDB <urlopen error ftp error: error_perm('550 Failed to change directory.')>
Retrieving 3D map with id= 774 failed retrying (1/3)
Error: [Errno 2] No such file or directory: './emd_774.map.gz'
Error retrieving data from EMDB <urlopen error ftp error: error_perm('550 Failed to change directory.')>
Retrieving 3D map with id= 774 failed retrying (2/3)
Error: [Errno 2] No such file or directory: './emd_774.map.gz'
Error retrieving data from EMDB <urlopen error ftp error: error_perm('550 Failed to change …
```

fetch_emdb_map fix for short ids

---

pwem/protocols/protocol_import/volumes.py

Using an old map, 2688, where the sampling rate isn't so well defined, I got the following error:
```
Scipion v3.0.10 - Eugenius
** Running command:  ipython 
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from pwem.protocols.protocol_import.volumes import fetch_emdb_map
In [2]: localFileName, sampling, origin = fetch_emdb_map(2688, directory='.', tmpDirectory='.')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-bc198a168cfc> in <module>
----> 1 localFileName, sampling, origin = fetch_emdb_map(2688, …
```

fixed fetch_emdb_map print error

---

pwem/viewers/plotter.py

This allows plotViewer to be given kwargs to get passed on to imshow. Previously, it could take kwargs but they weren't used anywhere. 
I showed it worked by giving origin='upper' in scipion-em-prody (line 103 of https://github.com/scipion-em/scipion-em-prody/blob/master/prody2/viewers/viewer_compare.py)

plotMatrix pass on kwargs

---

pwem/viewers/viewer_fsc.py

In the present implementation, the function calculateResolution() (line 121) does not pass the threshold parameter. Therefore, the default value 0.143 is always used. 
Not passing the threshold value have two effects:
1) the user cannot select it
2) the viewer will not draw the plot if the value of the FSC for all points is always greater than 0.143

pass parameter "self.threshold" to the viewer

---

CHANGES.txt
pwem/__init__.py
pwem/protocols/protocol_boxsize_parameters.py
pwem/tests/protocols/test_protocol_boxsize_parameters.py

This was done for sanity check since some of the output parameters where sensible to this condition (i.e. box size in 2D Classification).

Protocol boxsize related parameters outputs even number values

---

pwem/convert/atom_struct.py

Dear all,
here you have a second more complete version of the method getStructureBFactorValues to get two different lists including B-factor values. In addition to the previous one (list of each atom B-factors), we have a second list that associates each residue with the average of the B-factor values of all atoms in the residue. This second list is in fact a list of lists including for each residue: [Model, chain, residue order number, residue name, average B-factor].

Completed the method getStructureBFactorValues

---

CHANGES.txt
pwem/constants.py
pwem/wizards/wizard.py
pwem/wizards/wizards.py

Variable wizard with customizable target, input and output parameters. 
Gives flexibility, avoiding unnecessary inheritances just for changing param names
Example of the functioning with the replacement of the current wizard for selecting structure chains and residues (uses of the previous wizard corrected in other plugins respective PR)

Variable wizard

---

pwem/protocols/protocol_ctf_assign.py

Could be used when particles were ctf refined and then re-extracted, so that per-particle ctf is lost.

add option to assign from ptcls set

---

pwem/objects/data.py
pwem/viewers/viewers_data.py

This object is just a way of giving outputs a clearer name for better interpretation of results
Principal components aren't really that different from normal modes. The way of calculating them is different and the eigenvalues are the variance not its inverse, but that's all.
I now have a PCA protocol and pipeline and also some handling of eigenvalue order in the import modes protocol too: https://github.com/scipion-em/scipion-em-prody/pull/26

JMK added SetOfPrincipalComponents

---

pwem/protocols/protocol_sets.py

Missing 'includeBasic' parameter in overwritten method from base class.

Missing include basic

---

pwem/protocols/protocol_import/volumes.py

If there are different folders with atomic structure files with the same name that get selected with wild cards then they would overwrite each other previously. 
Now, if there's already something with that name then we add a number e.g. atoms.pdb becomes atoms2.pdb if atoms.pdb is already there.

add number to SetOfAS localPath to fix overwriting

---

CHANGES.txt
pwem/objects/data.py
pwem/protocols/protocol_extract_coordinates.py
pwem/protocols/protocol_import/coordinates.py
pwem/protocols/protocol_particles.py
pwem/tests/workflows/test_workflow_mixed.py

- Warning added in SetOfCoordinates.setMicrographs when not using an indirect pointer.
- Warning added in SetOfClasses.setImages when not using an indirect pointer.
- data.py test_workflow_mixed.py and uses logger instead of print
- Import coordinates fixed for complex streaming cases.
- Extract particles does not need SetOfMicrographs is "same as coordinates" is used.
CHANGES.txt updated

  - Allow indirect pointers in SetOfClasses.

---

pwem/viewers/viewers_data.py

SetOfPdbs was there but SetOfAtomStructs wasn't. Now that it's added, we can use this viewer for them.

add SetOfAtomStructs to DataViewer targets

---

pwem/emlib/metadata/utils.py

This PR improves performance when working with MetaData via Xmipp binding.
See also
https://github.com/I2PC/xmippCore/pull/147
https://github.com/I2PC/xmipp/pull/658

Using methods to read / write entire row, if available

---

pwem/convert/sequence.py
pwem/objects/data.py

When the sequence object is initialized, if no alphabet is defined it is set as None, but this breaks the construction of the SequenceHandler. We should either initialize the Alphabet to some value when creating the Sequence object if not provided or at least do not use the None for SequenceHandler.

UniProt typo and alphabet initialization for export

---

pwem/convert/sequence.py
pwem/objects/data.py

Sorry to reopen the PR, I messed it and didn't fix it with the last, somehow it didn't raise the same error but it did another.
Also, I am asking for a second change to not make the sequence cleaning by the SequenceHandler "compulsory". It was introduced in the new alphabet configuration and it messes with the way I had to visualize the alignments.  I am building fastas with dashes ("----") to align the structures and the cleaning removes them.

Refix alphabet is None.

---

CHANGES.txt
pwem/__init__.py
pwem/protocols/protocol_particles.py
pwem/viewers/__init__.py
pwem/viewers/plotter.py
pwem/viewers/viewer_angular_dist.py

-New Angular distribution viewer (right click on any SetOfParticles or SetOfSubtomograms will list it)
- Plotter.plotAngularDistribution refactored: uses scatter instead of plot for each point. It may improve performance.
- Plotter.plotAngularDistributionFromSet new: To plot sets with items.getTransform()

Angular dist viewer

---

CHANGES.txt
pwem/__init__.py
pwem/emlib/_libNone.py
pwem/objects/data.py

- Use new Config.isScipionRunning to print xmipp ghost message.
- SetOfImages._samplingRateStr extracted to convert sampling rate to a str
Needs: https://github.com/scipion-em/scipion-pyworkflow/pull/437

   - Use new Config.isScipionRunning to register file handlers.

---

pwem/protocols/protocol_import/sequence.py

Replaced UnitProt by UniProt (at least one case in which the protocol to import sequences (pwem/protocols/protocol_import/sequence.py) didn't work: G1U9Q8, HBB_MELGA)

Fixed typo

---

pwem/objects/data.py

Method `copyInfo` now detects if the type of objects involved in the copying process is equal. If this is the case, `copyInfo` will copy all attributes (including extended ones). Otherwise, a safe copy of only some attributes is performed.

Copy info method improvements

---

CHANGES.txt
pwem/constants.py
pwem/convert/headers.py
pwem/emlib/image/image_handler.py
pwem/tests/data/test_data.py

This fixes tiff dimensions now done with tifffile package for eer, tif, tiff and gain.
These are some results of my tests:
*Scipion*
pablo@youyou ~ $ scipion python
Scipion v3.3.0 - Eugenius
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwem.emlib.image import ImageHandler
>>> ih = ImageHandler()
>>> ih.getDimensions("/home/pablo/software/scipion/data/tests/movies/c3-adp-se-xyz-0228_200.tif")
(7676, 7420, 1, 38)
*eman*
pablo@youyou ~ $ scipion e2iminfo.py /home/pablo/software/scipion/data/tests/movies/c3-adp-se-xyz-0228_200.tif
Scipion v3.3.0 - Eugenius
eman/sparx command detected
/home/pablo/software/scipion/data/tests/movies/c3-adp-se-xyz-0228_200.tif	 38 images in TIFF format 	7676 x …

fix tiff dimensions

---

pwem/protocols/protocol_sets.py

default getObjDict has an extra para that joint set wasn¡t implementing. SInce it does not do anything different it is comented

fix getObjDict in join sets

---

pwem/viewers/viewer_chimera.py

Since chimeraX version has been updated to 1.6 we have added the following new variable:chimeraPythonFileName
All scripts using python commands must ending the file name in .py. Then we need to differentiate files using chimera commands from python commands. So, a new variable called chimeraPythonFileName has been defined to name files with python commands. Therefore the old variable chimeraScriptFileName will be used to name files with chimera commands:
chimeraPythonFileName = "chimeraScript.py"
chimeraScriptFileName = "chimeraScript.cxc"

new variable chimeraPythonFileName for chimeraX 1.6

---

CHANGES.txt
pwem/protocols/protocol_export/protocol_export_DB.py
pwem/tests/protocols/test_protocol_export2DB.py

When submitting  an atomic model to PDBe a list of matrices describing the symmetry need to be provided.
If this option is selected a file with this list of matrices is created

add symmetry option to export_DB protocol

---

CHANGES.txt
pwem/__init__.py
pwem/objects/__init__.py
pwem/objects/data_flexhub.py
pwem/protocols/__init__.py
pwem/protocols/protocol_base_flexhub.py

FlexHub data model has been moved to `scipion-em` to avoid extra dependencies of FlexHub related plugins to `scipion-em-flexutils`. The model includes:
- The FlexHub objects defined in `data_flexhub`
- The FlexHub base protocolo defined in `protocol_base_flexhub`. This protocol will be removed in the future to avoid having set creation methods

FlexHub data model moved to scipion-em

---

pwem/protocols/protocol_movie_eraser.py
pwem/tests/protocols/test_protocol_movie_eraser.py

modify protocol "movie_eraser". Now it handles 2 different cases
1) micrographs: if this input is selected all movies that have been used to create this setofmicrographs are deleted
2) coordinates: if this option is selected all movies are deleted except those  that have any particle (coordinate) assigned to them.
That is, in the first case processed movies are deleted (movies that have created micrographs) in the second empty movies are deleted (movies with no coordinates assigned to them.)
Test:
scipion3 tests pwem.tests.protocols.test_protocol_movie_eraser

Rm movie eraser

---

CHANGES.txt
pwem/protocols/protocol_particles.py

This protocol would not finish if both micrographs and ctf sets where closed, however there is a possibility that you were using trigger points so you dont want to use all your data, when this happened even though the input coordinates set was closed it had to wait until all the micrographs and ctfs that where not associated to those coordinates to finish. Now it will check if the input coords are closed and if you have all the ctfs and mics from the input already processed to finish without waiting for all to finish.

Extract coordinates: modify ending condition

---

CHANGES.txt
pwem/__init__.py
pwem/constants.py
pwem/protocols/protocol_set_editor.py
pwem/protocols/protocol_sets.py

V3.9.1:
Users:
- Fix: CrossSubset protocol works with "id" or "_objId" field too.
- Fix: Edit set protocol works with complex sets (titlseries, Classes2d) but not editing subelements for now.
Developers:
- New constants for "id" and "_objId": ID_COLUMN='id', ID_ATTRIBUTE='_objId'

Fix edit set

---

pwem/convert/atom_struct.py
pwem/protocols/protocol_import/volumes.py

Hi all,
two files have been changed  regarding the format of atom structure files:
1.- volumes.py: Conversion of imported .pdb files into .cif through ChimeraX (the flag --nogui avoids opening ChimeraX GUI)
2.- atom-struct.py: Replaces the use of .pdb file by the .cif file when the first one fails and the second one also exists in the same folder.

Changes in atom structure file format

---

CHANGES.txt
pwem/__init__.py
pwem/protocols/protocol_import/images.py

The button callback needed context. It was broken.

Hotfix: STOP_STREAMING import button fixed

---

pwem/objects/data.py

Relion intermediate iterations can have particles with classId=0 that do not have any class assignment yet. These should be skipped when creating classes

skip creating class2D is classId=0

---

pwem/protocols/protocol_import/volumes.py

This PR was opened with the initial issue of `pwem.Domain.importFromPlugin` not raising the appropiate exception class.
See referenced [pyworkflow's PR](https://github.com/scipion-em/scipion-pyworkflow/pull/582).
Function `importFromPlugin` does not look like is actually needed for the purpose of the `createOutputStep` function.
Instead, it is simpler (and therefore, less likely to fail), to just import the regular way and capture the possible exception the exact same way it was being done already.
If module chimera does not exist, this will raise a `ModuleNotFoundError`, and, if for some reason, module chimera does not have name Plugin, that will raise an `ImportError`. However, as `ImportError` is parent class for `ModuleNotFoundError`, capturing it will capture both of them.

Remove importFromPlugin function usage

---

CHANGES.txt
pwem/protocols/protocol_import/micrographs.py

Now it does not expect an specific name convention for the acquisition information. Enhancement reported by the ESRF facility.

Generalize loadAcquistionInfo method
