scipion-em/scipion-em

pwem/viewers/showj.py, pwem/viewers/viewer_volumes.py
=> fix showJ not showing volume slices.

pwem/convert/headers.py, pwem/protocols/protocol.py, pwem/viewers/viewers_data.py
=> Migration-to-py3: issues fixed in headers.py, protocol.py and

pwem/__init__.py, pwem/protocols/protocol_align_movies.py
Package level Scipion reference added
=> Fix moviealingment createOutput

pwem/__init__.py
Added pwem.Config and moved EM_ROOT and _defineEmVar
=> Moved EM_ROOT to here

pwem/viewers/views.py
This pull request adds a "save data" button to  the tables shown by scipion using the tableView class. If you press the button the data is saved in a *.csv file and displayed using openTextFileEditor. In my computer that means using gnumeric.
No new test have been created since I do not know how to emulate a click on a button.
follows a small script to check that everything is OK
scipion3 run python
from pwem.viewers import TableView
headerList = ['name', 'surname']
dataList = [
('John', 'Smith') ,
('Larry', 'Black') ,
('Walter', 'White') ,
('Fred', 'Becker')
]
msg = 'message to be shown at the table top'
title='window title'
#NOTE: the scripts assume that there is a Logs file in the directory in which you are working. This is #always true if you are running a protocol but for this small …
=> add save button to table view

pwem/convert/image_handler.py
Pull request for the wapper for the apply transform method into image handler.
This pull request includes a new method in the image handler class including the wrapper.
=> Fi feature xmipp apply transform wrapper

pwem/objects/data.py, pwem/viewers/plotter.py, pwem/viewers/showj.py, pwem/viewers/views.py
=> remove specific attrs

pwem/convert/headers.py, pwem/emlib/image/image_handler.py
Header reading fixed for movies.
File header reading case updated with isPG checking.
=> Fix header reading error when converting movies. Stack of volumes

pwem/constants.py, pwem/wizards/wizard.py
Frequency wizards --> Mousewheel masking, update layout, self-explicative
=> Jj update freq wiz

pwem/protocols/protocol_batch.py, pwem/protocols/protocol_sets.py
Removing hardcoded methods to create subsets(Allowing to create sub…sets of Tomograms and Subtomograms)
=> * Removing hardcoded methods to create subsets

pwem/__init__.py, pwem/objects/data.py
I thought that I have already created this PR.
=> Config expand

pwem/protocols/protocol_import/volumes.py, pwem/tests/protocols/test_protocols_import_volumes.py
Hi @delarosatrevin y @rsanchezgarc 
As promised I have added a new option to import volume: Now a 3D map  may be retrieved from EMDB. @rsanchezgarc since you ask for it review it.
test:  
scipion3 tests pwem.tests.protocols.test_protocols_import_volumes
look to import protoocl  called 'import vol,\n import from EMDB'
=> add new option to volume import. So we can retrieve maps from emdb

MANIFEST.in, setup.py
=> Fixing an error in MANIFEST.in

pwem/cmd/program.py, pwem/utils.py, pwem/viewers/showj.py, sonar-project.properties
This fixes emprogram allowing to run 3rd party commands under their environments using
emprogram <command>
In https://github.com/scipion-em/scipion-app/pull/56 "scipion run something" will end up calling emprogram.
=> fix running emprogram

pwem/viewers/showj.py
=> pass DEBUG MODE to java

pwem/tests/workflows/test_workflow_xmipp_ctf_consensus.py
=> fix_ctf_consensus_test

pwem/tests/workflows/test_workflow_xmipp_ctf_consensus.py
=> Including a test for new functionallity in CTFconsensus protocol

pwem/emlib/image/image_handler.py
This PR includes:
- Fixes in the description of the applyTransform method in ImageHandler
=> Fixes in imageHandler.applyTransform description

pwem/__init__.py, pwem/viewers/__init__.py, pwem/viewers/viewer_chimera.py
- Removed all code related with Chimera client connections
- Created axis, spheres and angular distributions files
- Updating the compatibility to ChimeraX
=> * Fixing an error showing the angular distribution

pwem/viewers/viewer_chimera.py
=> Replaced .cmd extension by .cxc

pwem/viewers/viewer_chimera.py
of a 3D map using another 3D map to set colors (for example the color of the pixels depend on the local resolution)
There are at least 5 places where this very same code has been used. I just deleted from the local viewers an placed in here plus updated it for chimerax
=> centralize chimera visualization

pwem/viewers/viewer_localres.py
This one is use, at least, by bsoft.
=> update viewer viewer_localres.py for chimerax

pwem/objects/data.py, pwem/protocols/protocol_batch.py
=> fix missing setof images pointer at set of classes

pwem/viewers/viewer_chimera.py, pwem/viewers/viewer_localres.py
Do not show axis for local resolution viewers
Tweaks to not show axis in local resolution viewers by default.
=> Do not write axis file if not to be shown

pwem/cmd/convert.py
Though relion picking wizards are gone, this fixes the star files names with coords
=> fix for relion

pwem/protocols/protocol_sets.py, pwem/tests/protocols/test_protocols_import_volumes.py
The protocol "pwem - join sets" has been modified to take several Volumes as input and create a SetOfVolumes as output.
=> Aj union set volumes

pwem/__init__.py, pwem/emlib/image/image_handler.py, pwem/tests/data/test_data.py
* Created a new method to scale a images stack using PIL
=> Creating a new method to scale a images stack using PIL

pwem/viewers/viewer_chimera.py, pwem/viewers/viewers_data.py
… folder is removed at the end of the protocol execution
=> * Changing the tmp folder path to the extra folder path

pwem/objects/data.py, pwem/protocols/protocol_sets.py
This just removes the usage or OrderedObject, deprecated in pyworkflow in the performance branch.
=> Performance

pwem/__init__.py, pwem/convert/transformations.py
New functionalities added to quaternion functions in convert
=> Quaternions

pwem/__init__.py, pwem/tests/__init__.py
This should fix #200 initializing the Datasets at plugin "initialization time.
Additionally, I've wrapped Dateset definition in a method to avoid "automatic" code execution that quite often, in other scenarios is causing us trouble.
=> define datasets at plugin initialization time.

pwem/protocols/protocol_sets.py
Iterating over ids instead of over items
Solves: https://github.com/scipion-em/scipion-em/issues/190
=> duplicatedIds issue

CHANGES.txt, pwem/__init__.py, pwem/objects/data.py, pwem/protocols.conf, pwem/protocols/__init__.py, pwem/protocols/protocol_set_filter.py, pwem/wizards/wizard.py, pwem/wizards/wizards.py
protocol tree (left pannel) collapsed at loading
protocols.conf created taken from scipion-app defining its own protocols.
version bumped
set filter does not work in streaming now (we might want that)
wizard result is the raw result from the eval which for booleans are 1 or 0 instead of True, False....we might want to make it more intuitive. Also, wizard deals with the first item but we might want to "navigate" through some items to test the formula with more items. A help also for non dev users might be useful too.
=> "set filter" protocol and wizard

CHANGES.txt, pwem/__init__.py, pwem/viewers/__init__.py, requirements.txt
=> Open more files with chimera

CHANGES.txt, pwem/emlib/image/image_handler.py, pwem/protocols/protocol_particles_picking.py
* Modifying insertFinalSteps in order to get the correct name of createOutput step
=> * Allowing to import .rec files

pwem/protocols/protocol_set_filter.py, pwem/tests/protocols/test_protocols_set_filter.py
Sorry, I accepted pull request #236  before submitted the modifications
=> use extended property properlly

CHANGES.txt, pwem/__init__.py, pwem/protocols/protocol_batch.py, pwem/protocols/protocol_sets.py, pwem/tests/protocols/test_protocols_sets.py
* Fixing an error creating user subsets
* Updating the package version
=> * Fixing an error creating user subsets

CHANGES.txt, pwem/protocols/protocol_set_filter.py
set filter fix when for not coordinates set.
=> changes.txt updated

CHANGES.txt, pwem/protocols/protocol_set_filter.py, pwem/tests/protocols/test_protocols_set_filter.py, pwem/wizards/wizards.py
Allow the filtering of a specified number/proportion of items with the highest/lowest values of a given attribute
=> Number and proportion of filtered items

pwem/tests/workflows/test_workflow_xmipp_ctf_consensus.py
Motivation: [scipion-users mail](https://sourceforge.net/p/scipion/mailman/scipion-users/thread/8dc7-6183ef00-5-426dda80%40251911506/#msg37379352)
=> ctf_consensus: delta in defocusU changed from 100 to 200

pwem/viewers/viewer_sequence.py
Default values for sequence attributes if empty to allow viewer
=> Default values if empty to allow viewer

pwem/convert/sequence.py, pwem/objects/data.py, pwem/protocols/protocol_import/sequence.py, pwem/tests/data/test_data.py
Added methods for writing fasta files for Sequence and SetOfSequences
=> Methods for writing fasta files for Sequence and SetOfSequences

pwem/viewers/viewer_chimera.py
Viewer for SetOfAtomStruct object.
=> viewer SetOfAtomStructs

pwem/protocols/protocol_sets.py, pwem/tests/data/test_metadata.py
* Adding a test to iterate over the metadata in a file
=> * Fixing an error creating a subset

pwem/viewers/viewer_localres.py
Residues and chains read from cif more robust
=> CIF chains and residue numbers read more robust

CHANGES.txt, pwem/protocols/__init__.py, pwem/protocols/protocol_tools.py, pwem/viewers/filehandlers.py
Adding the protocolo ProtManualCheckpoint that kept running for a time determined by a parameter or until the user determines it is convenient
=> * Adding the protocolo ProtManualCheckpoint

pwem/viewers/viewer_localres.py
Function to write a temporal CIF with attribute as occupancy external to viewer class
=> Attr viewer

pwem/protocols/protocol_align_movies.py
=> add even/odd support for SPA motioncor

pwem/protocols/protocol_sets.py
Makes renumber option clearer and fixes some readability things for remove duplicates
=> join sets help fixes

pwem/objects/data.py
Only last item was appended because it was outside the loop
=> Indentation fix importFromFile, setOfSequences

pwem/protocols/protocol_sets.py
This will allow creating a subset from scipion objects by setting a range of IDs. I did not modify the form in order not to affect other protocols that depend on this protocol.
=> creating a subset from specific ids

pwem/wizards/wizards.py
Fixed Wizard for SequenceVariants input
=> Fixed wizard for sequenceVariants

pwem/wizards/wizards.py
=> Old wizard for selecting structure chains is recovered

CHANGES.txt, pwem/__init__.py, requirements.txt
=> Fix scipy dependency conflict

pwem/viewers/viewer_localres.py
The attributes can be visualized over the sequence, not only over the structure
=> Attributes viewer include viewer of the attribute over the sequence

pwem/protocols/protocol_origin_sampling_volume.py
Improve help for the copy option
=> Update copy option help

CHANGES.txt
I added the changes.txt line you ask me for, sorry I was late and I have done it after the merge
=> changes.txt

CHANGES.txt, pwem/protocols/protocol_import/volumes.py
Code separated EMDB vs File
logging used.
Possible outputs defined.
Url to get EMDB metadata updated. The previous one was failing.
More consistent when failing. Now protocol also fails.
=> Fix import volumes

pwem/wizards/wizards.py
just one very little fix more...
=> Sequence residue selection wizard

pwem/protocols/protocol_align_movies.py
See also https://github.com/I2PC/scipion-em-xmipp/pull/603
=> averageMovie: removed as it's no longer used

CHANGES.txt, pwem/protocols.conf, pwem/protocols/__init__.py, pwem/protocols/protocol_boxsize_checkpoint.py, pwem/tests/protocols/test_protocol_boxsize_checkpoint.py
Protocol to compare two particles box size
=> New protocol boxsize checkpoint

CHANGES.txt, pwem/__init__.py, pwem/viewers/plotter.py, pwem/viewers/showj.py, pwem/viewers/viewer_angular_dist.py
- showj.py: javaVersion cached, javaBin taken from Config.JAVA_HOME o "java"
- showj.py: SCIPION_JAVA_HOME takes priority over JAVA_HOME (pycharm debugging case)
=>    - showj.py: uses logger

pwem/protocols/protocol_import/dataimport.py, requirements.txt
* Keeping original base names
- changing only those that are repeated
* Removing python-slugify dependency
=>  Keeping original base names

CHANGES.txt, pwem/protocols/protocol_import/volumes.py, pwem/viewers/filehandlers.py
- Import volumes set the volume comment to the original file.
=>  - The browser thumbnail show origin info for mrc files

CHANGES.txt, pwem/objects/data.py, pwem/viewers/__init__.py, pwem/viewers/viewer_chimera.py, pwem/viewers/viewers_data.py
Chimera viewer handles also SetOfVolumes and SetOfClasses3D
=> Remove ang dist viewer

pwem/convert/atom_struct.py, pwem/protocols/protocol_import/sequence.py
Fixed typo in import-sequence protocol to make uniform the name of NCBI GenBank and fixed one of the tests with the appropriate sequence description. Test to check changes:
scipion3 tests pwem.tests.protocols.test_protocols_import_sequence.TestImportSequence
=> Rm sequence

pwem/__init__.py, pwem/protocols/protocol_import/sequence.py
added dependencies to maxit installation
neededProgs=['gcc', 'flex', 'make', 'bison', 'tcsh'],
=> Rm fixtypo

pwem/objects/data.py
AS volumes cannot be set with Volume subclasses like Subtomogram Averages.
Would it make sense to allow it?
=> Fix setVolume in AS object

pwem/protocols/protocol_batch.py
Fixes an error when creating subsets of particles or volumes from classes, which not were initialized to the appropriate type.
=> Fix classes subset object type

pwem/protocols/protocol_import/volumes.py
It could be that we want to set the origin when we import from id
=> remove condition importFrom file on setOrigCoord

pwem/wizards/wizards.py
Just to handle wizard errors when empty input
=> Raise exception when input is empty

CHANGES.txt, pwem/__init__.py, pwem/objects/data.py, pwem/protocols/protocol_import/coordinates.py, pwem/viewers/filehandlers.py
=> SetOfCoordinates tweaks

CHANGES.txt, pwem/__init__.py, pwem/objects/data.py, pwem/protocols/__init__.py
- add attribute issubParticles to set OfParticles
- modify __str__ to print setOfSubPArticles when appropiate
- remove setOf in __str__
=> add issubparticle to setofparticles and remove setOF

CHANGES.txt, pwem/__init__.py, pwem/emlib/image/image_handler.py, pwem/objects/data.py, pwem/protocols/protocol_batch.py, pwem/tests/protocols/test_plugin.py, pwem/viewers/filehandlers.py, pwem/viewers/viewer_chimera.py, requirements.txt
- Windows' ChimeraX properly called from WSL installations
- EMSet.copyItems and createCopy accepts "itemSelectedCallback" falling back to isEnabled.
- getVersionFromPath improved: works with cuda-11.4.safe (uses regex looking up for numbers)
=>      - Fix: CTFTomoSeries manual subset should work

pwem/tests/__init__.py
Otherwise these files can't be loaded anymore
=> fix model_building_tutorial dataset pdb1 location

pwem/constants.py, pwem/emlib/image/image_readers.py
Use Xmipp for getting dimensions of old volumes with .map extension
=> Solved dims problem with .map volumes

pwem/protocols/protocol_3d.py
This doesn't actually affect anything but it's still good to be consistent
=> fix prot 3d operation docstr

CHANGES.txt, pwem/__init__.py, pwem/emlib/image/image_readers.py, pwem/tests/data/test_data.py
To match xmipp https://github.com/I2PC/xmippCore/blob/devel/core/rwTIFF.cpp#L224
Closes #475
=> Fix tif reader

pwem/tests/__init__.py
I've tried to check both all scipion-em and I2PC repos for those keys. In case I delete some by mistake, they can be recovered.
=> removing unused keys from test datasets

CHANGES.txt, pwem/__init__.py, pwem/emlib/image/image_readers.py, pwem/viewers/filehandlers.py, pwem/viewers/mdviewer/readers.py, pwem/wizards/wizard.py, requirements.txt
Thes needs pyworkflow sprites branch
=> Adapted to sprites

pwem/tests/workflows/test_parallel_gpu_queue.py
Comment part of a test that is not used and could cause conflict with a pyworkflow PR (Step queue executor: fix stop protocol action)
=> Step queue executor: comment conflictive test

CHANGES.txt, pwem/emlib/image/image_readers.py, pwem/objects/data.py, pwem/viewers/__init__.py, pwem/viewers/mdviewer/readers.py, pwem/viewers/mdviewer/volumeViewer.py, pwem/viewers/viewer_coordinates.py, requirements.txt
* Adding a new 2D coordinate viewer.
* Updating the classifyItems method:
- adding a boolean flag indicating whether to raise an exception if there is a failure while attempting to retrieve the next element 
from itemDataIterator.
*  Updating the STKImage Reader:
- reading a .stk file without the id@ ...
=> Coords viewer

pwem/emlib/image/image_readers.py, pwem/viewers/mdviewer/readers.py, pwem/viewers/mdviewer/viewer.py, pwem/viewers/viewers_data.py
- Renaming the viewers name
- Updating the MRC image reader to show a specific slice in a volume
=>  - Renaming the viewers name

pwem/viewers/viewer_localres.py
The colormap of the histogram and the color selection were flipped (ups!)
=> Viewer color fixed

pwem/tests/__init__.py
pwem.tests.workflows.test_workflow_mixed_large is failing because of missing keys
=> rescue few missing keys

pwem/objects/data.py, pwem/protocols/protocol_sets.py
Should not change any functionality, but still good to have
=> fix setCoordinates docstring and protocol sets warning messages

CHANGES.txt, pwem/viewers/mdviewer/readers.py, pwem/viewers/mdviewer/star_dao.py
* Allowing to create subsets from the selection in the metadataviewer plotter
* Fixing an error creating subset through new metadataviewer
=>  * Allowing to create subsets from the selection in the metadataviewer plotter

CHANGES.txt, pwem/__init__.py, pwem/objects/data.py, pwem/protocols.conf, pwem/protocols/protocol_sets.py
NEW PROTOCOL - data summary: Aggregates (COUNT, MAX, MIN, AVG) any set data based on its fields
=> Fix em variable wrong expansion

pwem/protocols/protocol_import/coordinates.py
Closes #496 
This unifies Relion import from both single particles.star file and multiple coordinates.star files.
=> update relion coords import

pwem/viewers/mdviewer/readers.py
Taking into account the labels visible only for the object table
=> Visible columns

requirements.txt
pillow and matplotlib are required for pw, and pw is required for pwem.
=> delete duplicated requirements

CHANGES.txt, pwem/objects/data.py, pwem/viewers/viewer_volumes.py
Closes #513 and https://github.com/scipion-em/scipion-pyworkflow/issues/512
=> Fix volume halfmaps wrong filename

CHANGES.txt, pwem/__init__.py
Version bumped and changes properly updated
=> Pconesa patch 1

CHANGES.txt, pwem/protocols/parallel.py, pwem/protocols/protocol_create_stream_data.py, pwem/protocols/protocol_micrographs.py, pwem/protocols/protocol_movies.py, pwem/tests/protocols/test_protocols_import_coords.py
=> Execution mode

CHANGES.txt, pwem/objects/data.py, pwem/protocols/protocol_set_editor.py, pwem/protocols/protocol_sets.py
- Edit set protocol works with complex sets (titlseries, Classes2d) using "Sub item
=> Edit subitems

CHANGES.txt, pwem/__init__.py, pwem/objects/data.py, pwem/viewers/mdviewer/sqlite_dao.py
- Adding a prefix to the calculated columns for the metadataviewer
=> Mdviewer cols prefix

CHANGES.txt, pwem/objects/data.py
Adding a boolean flag that determines whether the classification process should skip the next item
=> Adding a boolean flag that determines whether the classification process should skip the next item

pwem/objects/data.py
* Fix an error copying items from another set
* Adding other parameters to copyItems method(orderBy and direction)
=> Fix an error copying items from another set

CHANGES.txt, pwem/convert/pdb_list.py, pwem/convert/transformations.py, pwem/emlib/image/image_readers.py, pwem/tests/protocols/test_projection_edit.py, pwem/tests/protocols/test_protocol_export2DB.py, requirements.txt
Needs debug branch from pyworkflow
=>   - __debug__ enable; assert commands replaced by if not + raise.

pwem/objects/data.py
Reverts scipion-em/scipion-em#581
=> Revert "Fixing Euler angle convention in getEulerAngles()"
